apiVersion: apps/v1
kind: Deployment 
metadata:
  name: frontend-deployment
  labels:
    type: frontend-deployment

spec:
  replicas: 4
  selector:
    matchLabels:
      type: frontend-deployment
  template:
    metadata:
      labels:
        type: frontend-deployment
    spec:
      containers:
        - image: httpd
          name: httpd
