apiVersion: v1
kind: Pod
metadata: 
  name: nginx
  namespace: mynamespace
  labels:
    app: nginx
spec:
   containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
      